### ISSUE TITLE
Remove "Auto generated by Gybson on [EXACT DATE]" on 'gybson generate' command

### ISSUE THREAD

**Issue by lfa9603** [MattGson/Gybson#4]
<img width="587" alt="Screen Shot 2020-07-27 at 3 15 29 PM" src="https://user-images.githubusercontent.com/36972588/88500169-0af96680-d01c-11ea-8077-99417a581552.png">

The autogen of this string causes n file changes per PR where n is the number of tables in the db even when no change to the table was made.

Remove to avoid continously polluting the PRs.

**Comment by MattGson** [comment]
It might be worthwhile trying to include some kind of diff-checker so that new files are updated while unchanged files are left.
